name: Build Unsigned IPA
on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Expo & Dependencies
        run: |
          npm install -g expo-cli
          cd client && npm install

      - name: Expo Prebuild
        run: cd client && npx expo prebuild --platform ios

      - name: Build Unsigned App
        run: |
          cd client/ios
          xcodebuild -workspace *.xcworkspace \
                     -scheme client \
                     -configuration Release \
                     -sdk iphoneos \
                     -destination 'generic/platform=iOS' \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO \
                     AD_HOC_CODE_SIGNING_ALLOWED=YES \
                     clean build

      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -r client/ios/build/Release-iphoneos/client.app Payload/
          zip -r GPSMock.ipa Payload

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: Unsigned-IPA
          path: GPSMock.ipa
